import { MessageSquareText } from 'lucide-react';

const transcript = [
  { time: '19:42', speaker: 'Lecturer', text: 'The repository should abstract persistence, not contain business rules.', topic: 'Architecture' },
  { time: '20:08', speaker: 'Student · Amaya', text: 'So the service can swap the database without changing the use case?', topic: 'Clarification' },
  { time: '20:21', speaker: 'Lecturer', text: 'Exactly. That is the dependency inversion principle in practice.', topic: 'Key concept' },
  { time: '21:04', speaker: 'Student · Ravin', text: 'Would a mock repository be useful for our unit tests?', topic: 'Application' },
];
export default function TranscriptStream() { return <div className="rounded-2xl border border-slate-200/80 bg-white/80 p-5 font-mono shadow-md shadow-slate-200/50 backdrop-blur-xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-cyan-600">Live transcript</p><h2 className="mt-1 text-lg font-bold text-slate-900">Conversation stream</h2></div><span className="flex items-center gap-1.5 text-xs font-semibold text-emerald-600"><span className="h-2 w-2 animate-pulse rounded-full bg-emerald-500" />AI classified</span></div><div className="mt-5 space-y-4">{transcript.map((line) => <div key={`${line.time}-${line.speaker}`} className="flex gap-3"><span className="w-10 pt-1 text-[11px] text-slate-400">{line.time}</span><div className="relative flex-1 rounded-xl border border-slate-200 bg-slate-50/80 p-3"><div className="flex items-center justify-between gap-2"><span className={`text-xs font-bold ${line.speaker.startsWith('Lecturer') ? 'text-cyan-600' : 'text-amber-600'}`}>{line.speaker}</span><span className="rounded-full bg-cyan-50 px-2 py-0.5 text-[10px] font-semibold text-cyan-700 ring-1 ring-cyan-200">{line.topic}</span></div><p className="mt-2 text-sm leading-5 text-slate-700">{line.text}</p></div></div>)}</div><button type="button" className="mt-5 flex w-full items-center justify-center gap-2 rounded-lg border border-slate-200 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50"><MessageSquareText className="h-4 w-4" />Open full transcript</button></div>; }
