using System;

namespace ACM.Backend.Core.Entities
{
    public class DialogueTurn
    {
        public Guid Id { get; set; } = Guid.NewGuid();
        
        // Foreign Key linking back to the StudySession
        public Guid SessionId { get; set; }
        public StudySession Session { get; set; } // Navigation property
        
        public SpeakerType Speaker { get; set; }
        
        // The text transcribed from the audio (or generated by AI)
        public string Text { get; set; } 
        
        // Where we save the .m4a file on the server/cloud
        public string? AudioFilePath { get; set; } 
        
        public DateTime Timestamp { get; set; } = DateTime.UtcNow;
    }

    public enum SpeakerType
    {
        Student,
        AI_Socratic,
        AI_Pedant,
        AI_Novice
    }
}